USE QLBongDa
GO

-- e.
CREATE PROCEDURE dbo.SP_SEL_NO_ENCRYPT
	@TenCLB NVARCHAR(100),
	@TenQG NVARCHAR(60)

AS
BEGIN
	SELECT CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, CT.VITRI
	FROM CAUTHU AS CT
	LEFT JOIN CAULACBO AS CLB
	ON CT.MACLB = CLB.MACLB
	LEFT JOIN QUOCGIA AS QG
	ON CT.MAQG = QG.MAQG
	WHERE CLB.TENCLB = @TenCLB AND QG.TENQG = @TenQG
END
GO

-- f.
CREATE PROCEDURE dbo.SP_SEL_ENCRYPT
	@TenCLB NVARCHAR(100),
	@TenQG NVARCHAR(60)
WITH ENCRYPTION
AS
BEGIN
	SELECT CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, CT.VITRI
	FROM CAUTHU AS CT
	LEFT JOIN CAULACBO AS CLB
	ON CT.MACLB = CLB.MACLB
	LEFT JOIN QUOCGIA AS QG
	ON CT.MAQG = QG.MAQG
	WHERE CLB.TENCLB = @TenCLB AND QG.TENQG = @TenQG
END

-- drop for testing
--DROP PROCEDURE SP_SEL_NO_ENCRYPT
--GO
--DROP PROCEDURE SP_SEL_ENCRYPT
--GO

-- g. execute
EXEC SP_SEL_NO_ENCRYPT N'SHB Đà Nẵng', N'Brazil'
GO

EXEC SP_SEL_ENCRYPT N'SHB Đà Nẵng', N'Brazil'
GO

-- h. 
DECLARE @proc_name VARCHAR(100) = 'SP_SEL_%' -- Replace with the pattern of your procedure name
DECLARE @proc_schema VARCHAR(100) = 'dbo' -- Replace with the schema of your procedures
DECLARE @sql NVARCHAR(MAX)

DECLARE cur CURSOR FOR
    SELECT name
    FROM sys.procedures
    WHERE name LIKE @proc_name AND SCHEMA_NAME(schema_id) = @proc_schema

OPEN cur

FETCH NEXT FROM cur INTO @proc_name

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @sql = 'ALTER PROCEDURE ' + QUOTENAME(@proc_schema) + '.' + QUOTENAME(@proc_name) + ' WITH ENCRYPTION'
    EXEC sp_executesql @sql

    FETCH NEXT FROM cur INTO @proc_name
END

CLOSE cur
DEALLOCATE cur
GO
-- i.
----  1.
CREATE VIEW dbo.vCau1 
AS
	SELECT CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, CT.VITRI
	FROM dbo.CAUTHU AS CT
	LEFT JOIN dbo.CAULACBO AS CLB
	ON CT.MACLB = CLB.MACLB
	LEFT JOIN QUOCGIA AS QG
	ON CT.MAQG = QG.MAQG
	WHERE CLB.TENCLB = N'SHB Đà Nẵng' AND QG.TENQG = N'Brazil'
GO

---- 2.
CREATE VIEW dbo.vCau2 
AS
	SELECT TD.MATRAN, TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2
	FROM dbo.TRANDAU AS TD
	LEFT JOIN dbo.SANVD AS SVD
	ON TD.MASAN = SVD.MASAN
	LEFT JOIN dbo.CAULACBO AS CLB1
	ON TD.MACLB1 = CLB1.MACLB 
	LEFT JOIN dbo.CAULACBO AS CLB2
	ON TD.MACLB2 = CLB2.MACLB
	WHERE TD.VONG = 3 AND TD.NAM = 2009
GO

---- 3.
CREATE VIEW dbo.vCau3
AS
	SELECT X.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, X.VAITRO, CLB.TENCLB
	FROM HLV_CLB AS X
	LEFT JOIN dbo.HUANLUYENVIEN AS HLV
	ON X.MAHLV = HLV.MAHLV
	LEFT JOIN dbo.QUOCGIA AS QG
	ON HLV.MAQG = QG.MAQG
	LEFT JOIN CAULACBO AS CLB
	ON X.MACLB = CLB.MACLB
	WHERE QG.TENQG = N'Việt Nam'
GO

---- 4.
CREATE VIEW dbo.vCau4
AS
	SELECT clb.MACLB, clb.TENCLB, svd.TENSAN, svd.DIACHI, COUNT(*) AS SOCAUTHU
	FROM dbo.CAULACBO AS clb
	LEFT JOIN dbo.SANVD AS svd
	ON clb.MASAN = svd.MASAN
	JOIN dbo.CAUTHU AS ct
	ON ct.MACLB = clb.MACLB
	LEFT JOIN dbo.QUOCGIA AS qg
	ON ct.MAQG = qg.MAQG
	WHERE qg.TENQG <> N'Việt Nam'
	GROUP BY clb.MACLB, clb.TENCLB, svd.TENSAN, svd.DIACHI
	HAVING COUNT(*) >= 2;
GO

---- 5.
CREATE VIEW dbo.vCau5
AS
	SELECT t.TENTINH, Count(*) AS SOLUONGTIENDAO
	FROM dbo.TINH AS t
	JOIN dbo.CAULACBO AS clb
	ON T.MATINH = clb.MATINH
	JOIN CAUTHU AS ct
	ON clb.MACLB = ct.MACLB
	WHERE ct.VITRI = N'Tiền đạo'
	GROUP BY t.TENTINH
GO

---- 6.
CREATE VIEW dbo.vCau6
AS
	SELECT clb.TENCLB, t.TENTINH
	FROM dbo.BANGXH AS bxh
	JOIN dbo.CAULACBO AS clb
	ON bxh.MACLB = clb.MACLB
	JOIN dbo.TINH AS t
	ON clb.MATINH = t.MATINH
	WHERE bxh.VONG = 3 AND bxh.NAM = 2009
	AND bxh.HANG = (
		SELECT MIN(HANG)
		FROM dbo.BANGXH
		WHERE VONG = 3
		)
GO

---- 7.
CREATE VIEW dbo.vCau7
AS
	SELECT hlv.TENHLV
	FROM dbo.HUANLUYENVIEN AS hlv
	LEFT JOIN HLV_CLB AS X
	ON hlv.MAHLV = X.MAHLV
	WHERE hlv.DIENTHOAI IS NULL
GO

---- 8.

--- DROP VIEW FOR TESTING
DROP VIEW dbo.vCau1
DROP VIEW dbo.vCau2
DROP VIEW dbo.vCau3
DROP VIEW dbo.vCau4
DROP VIEW dbo.vCau5
DROP VIEW dbo.vCau6
DROP VIEW dbo.vCau7